### PR TITLE
Several bugfixes

### PR DESCRIPTION
**Pull request by philvdb**
see #38

### CODE REVIEW

**Comment by philvdb** [comment]
In my setting, I have greatly extended the class FrontendUser with several functions, one of them is a final save() on __destroy(). If you're using the MemberModel() to save avatar data, it gets overwritten by FrontendUser->save() and thus never saved. Of course you may not care about this incompatibility, but what is the harm in using the native FrontendUser to save an uploaded avatar?

**Comment by philvdb** [comment]
In the backend, I get a fatal error if there is no fallback avatar image defined in the settings. This hard crash seems a little harsh, we might just use the default images you provide in the module. See commit above.

**Comment by philvdb** [comment]
This last one looked rather funny when you are displaying a long list of avatars in the frontend using the insert tag, some of whom haven't uploaded a picture yet. If you are logged in as a female member, all **other** default avatars will be female due to this bug. Same is true if you are logged in as a male but that doesn't really stand out as pinkly ;)

**Comment by katgirl** [comment]
Please at single Pull-Reqest and at develop branch

**Pull request closed without merging**
